CREATE TABLE IF NOT EXISTS request_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id TEXT NOT NULL UNIQUE,
    username TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('waiting', 'processing', 'completed', 'error')),
    message TEXT,
    uid TEXT,
    product_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_request_history_created_at
ON request_history (created_at DESC);
